/** All user-facing copy, in one place for future i18n. */
export const STR = {
  brand: "LayoverLab",
  tagline:
    "The cheapest way from A to B is sometimes three days in a country you have never heard of.",
  heroSub:
    "Self-transfer combos, multi-day stopovers, nearby airports, ground corridors — we search the routes booking sites won't show you.",
  tryExample: "Try a weird route:",
  howItWorksTitle: "How it works",
  howItWorks: [
    {
      title: "We crawl real fares",
      body: "Budget airlines, aggregators and ground corridors feed one big fare graph, refreshed continuously.",
    },
    {
      title: "We search creative paths",
      body: "Multi-day stopovers, self-transfer combos and nearby airports — not just what one airline sells.",
    },
    {
      title: "We verify before you book",
      body: "Top candidates are re-checked live. Anything not verified is clearly labeled as a cached estimate.",
    },
  ],
  form: {
    from: "From",
    to: "To",
    swap: "Swap origin and destination",
    dates: "Departure window",
    pickDates: "Pick a date range",
    presetNextMonth: "Next month",
    presetSummer: "Whole summer",
    maxStopoverNights: "Max stopover nights",
    maxStops: "Max stops",
    roundTrip: "Round trip",
    stay: "Stay",
    stayTo: "to",
    stayDays: "days",
    submit: "Find weird cheap routes",
    submitBusy: "Searching…",
    missing: "Missing:",
    missingOrigin: "origin",
    missingDest: "destination",
    missingDates: "dates",
    missingDateOrder: "dates (from is after to)",
    airportPlaceholder: "City, airport or IATA",
    recentSearches: "Recent",
  },
  status: {
    searchingCache: "Searching cached fares…",
    verifying: "Live-verifying the best candidates…",
    crawling: "Fetching fresh prices from airlines… results improve live",
    elapsed: (s: number) => `${s}s elapsed`,
    updated: "Found cheaper routes — updated",
    doneCrawlPending: "Still crawling this route — re-run in a minute for more results.",
    reSearch: "Search again",
    retry: "Retry search",
    errorTitle: "Search failed.",
    errorBody:
      "The connection to the search stream was lost. If the fare cache is empty, the crawler may still be collecting prices for this route.",
    noResults:
      "No routes in the cache for this search yet. The crawler has been notified and is fetching fares for this route now — try again in a few minutes.",
    ariaResults: "Search results",
  },
  filters: {
    title: "Filters",
    maxStops: "Max stops",
    maxStopoverNights: "Max stopover nights",
    verifiedOnly: "Verified only",
    sort: "Sort",
    sortCheapest: "Cheapest",
    sortFewestStops: "Fewest stops",
    sortShortest: "Shortest",
    noneMatch: "No results match the current filters.",
  },
  savings: (amount: string) => `Save ${amount} vs the best direct flight in these results`,
  card: {
    verifiedNow: "verified now",
    cached: "cached",
    cachedTooltip: "Prices from the fare cache — verify before booking",
    legs: (n: number) => `${n} leg${n > 1 ? "s" : ""}`,
    stopoverNights: (n: number) => `${n} stopover night${n > 1 ? "s" : ""}`,
    directIsh: "direct-ish",
    notes: (n: number) => `${n} note${n !== 1 ? "s" : ""}`,
    share: "share",
    shareCopied: "Link copied to clipboard",
    shareError: "Could not create a share link",
    details: "details",
    hideDetails: "hide details",
    book: "Book",
    total: "Total",
    nightsIn: (nights: number, place: string) => `${nights} night${nights > 1 ? "s" : ""} in ${place}`,
    departure: "dep",
    arrival: "arr",
    freshness: "fetched",
    warnings: {
      danger: "Risks",
      caution: "Check before booking",
      info: "Good to know",
    },
  },
  permalink: {
    back: "New search",
    title: "Shared itinerary",
    loading: "Loading and re-verifying prices…",
    notFound: "This itinerary does not exist (or the API is unreachable).",
    reverified: "Prices were re-checked when you opened this link. The original snapshot may have differed.",
    copyLink: "Copy link",
    copied: "Link copied",
    nativeShare: "Share",
  },
  footer:
    "Prices are estimates from cached public data until marked verified. Self-transfer trips are separate tickets: missed connections are your risk. Always confirm the final price on the booking site.",
} as const;
